name: DevSecOps CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------------------------
      # 🔍 SECRET SCANNING (Gitleaks)
      # ---------------------------
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2

      # ---------------------------
      # 🐍 Python setup
      # ---------------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install fastapi uvicorn

      # ---------------------------
      # 🐳 Docker build
      # ---------------------------
      - name: Build Docker image
        run: docker build -t user-service ./user-service

      # ---------------------------
      # 🛡️ TRIVY SCAN (Docker security)
      # ---------------------------
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: user-service
          format: table
          exit-code: 0
