---
name: DevSecOps CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:

  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install fastapi uvicorn

      - name: Build Docker image
        run: docker build -t user-service ./user-service

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: user-service
          format: table
          exit-code: 0


  deploy:
    needs: security
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Deploy to Kubernetes
        run: |
          echo "Deploy step (we will connect cluster later)"
          kubectl version --client
